name: DoctorPaulNYC
favicon: null
layout_spectrum: 0.9817
typography_spectrum: 0.49499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1e27'
    - '#ff0000'
    - '#7f0000'
    - '#000000'
    - '#bf003f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.507827709428966
  rhythmicContrast: 0.9700610125437379
purpose: []
