name: DoctorPaulNYC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.507827709428966
  rhythmicContrast: 0.9700610125437379
purpose: []
